### ISSUE TITLE
Elastest doesn't start in Docker for Windows

### ISSUE THREAD

**Issue by jaruzafa** [elastest/elastest#1]
Hi!
**Description**: 
I'm trying to run Elastest with Docker for Windows Version 17.09.1-ce-win42 (14687) but I got an error:
```
Error response from daemon: No such container: docker
Error: Unable to register Platform on the network
```

**Version**:
 ElasTest Platform 0.6.0-beta3
 Docker for Windows Version 17.09.1-ce-win42 (14687)

**Steps**:

- Start Docker
- Open a PowerShell console
- Run: `docker run --rm -v /var/run/docker.sock:/var/run/docker.sock elastest/platform start --server-address=localhost`

I got:
```
Pulling some necessary images...
3.7.1: Pulling from selenium/standalone-chrome-debug
Digest: sha256:fa237d16fa6af0ffcb9fa807803fac2051cfecb42b131d384cd3c30a8276871d
Status: Image is up to date for selenium/standalone-chrome-debug:3.7.1
3.7.1: Pulling from elastest/eus-browser-firefox
Digest: sha256:b66ac623f05deea9dae8778584de872b26661f9707fbcd99d591bf4542007319
Status: Image is up to date for elastest/eus-browser-firefox:3.7.1
0.6.0-beta3: Pulling from elastest/eus
Digest: sha256:7bff410d7eec4938f2d11103edfdd89e9a5f419fc1436ed4d332dd07603171ca
Status: Image is up to date for elastest/eus:0.6.0-beta3
Using default tag: latest
latest: Pulling from elastest/eus-novnc
Digest: sha256:912cca03b0b2b4b43140175b4c64dd0d6db09b927c970e1fedbf42b436c122c7
Status: Image is up to date for elastest/eus-novnc:latest
Using default tag: latest
latest: Pulling from elastest/etm-socat
Digest: sha256:967942a0127a74e1335e4478c94955f3b7ebc68ecfc84215a62f2e06d1fb5e40
Status: Image is up to date for elastest/etm-socat:latest

Starting ElasTest Platform 0.6.0-beta3
 (normal mode)...

Please wait a few seconds while we start the ElasTest services, the ElasTest URL will be shown when ready.

Error response from daemon: No such container: docker
Error: Unable to register Platform on the network
```

**Comment by franciscoRdiaz** [comment]
Hi @jaruzafa!

Please, let us know your Windows version and run the command again adding the argument '-l' to get more information.

Thanks!

**Comment by gortazar** [comment]
@jaruzafa can you please try to open on a browser the address `localhost:37000`? I'm trying with the same configuration as you, and I'm getting the same error but ElasTest is available anyway.

We will fix the error ASAP, but in the meanwhile at least you can try ElasTest. I've tried the HelloWorld project that comes by default with ElasTest and it just works.

**Comment by jaruzafa** [comment]
Hi @gortazar !  You're right, it worked despite the error message :) 
I've tried to run the Hello World example, but when I hit the run button it says: "Executing tests.." and then "Error". Sorry no more info is provided :(
I attach you the log I got with -l option that should cointain all my actions.
My OS is Windows 10 Pro.
My log: [elast.log](https://github.com/elastest/elastest/files/1604784/elast.log)

Thanks!

**Comment by franciscoRdiaz** [comment]
Hi @jaruzafa! 
It seems a synchronization error between two modules of the platform. 
While we solve the issue. Could you try to start ElasTest several times? 
It may not take more than two or three attempts to start corretly.

Please, let us know what happened.

PD: If Ctrl+C does not work to stop ElasTest try it with the stop command docker `run --rm -v /var/run/docker.sock:/var/run/docker.sock elastest/platform stop`

Thanks!

**Comment by EduJGURJC** [comment]
Hi @jaruzafa,

try to restart as you said @franciscoRdiaz and if you still having errors, try starting Elastest Platform development version (elastest/platform:dev).

Thanks

**Comment by jaruzafa** [comment]
Hi @EduJGURJC, 
I switched to development version and it worked at first run :)
Thanks!!
