### ISSUE TITLE
It shall be possible to open new browsers in a new tab

### ISSUE THREAD

**Issue by gortazar** [elastest/elastest#11]
Similar to what happens with recordings, when requesting a new browser from the GUI, there shall be an option to allow the user opening the browser in a new tab, instead of a dialog. 

As a plus, this would allow a user opening several browsers, something that is not possible at the moment.

**Comment by micaelgallego** [comment]
The best way to do it is implement feature #12 and let user open manual created browsers as dialog or tab

**Comment by EduJGURJC** [comment]
Available since [1.0.0-beta2](https://elastest.io/docs/releases/#1.0.0-beta2)
