### ISSUE TITLE
List of opened browsers shall appear in the Web Browsers tab

### ISSUE THREAD

**Issue by gortazar** [elastest/elastest#12]
The list of opened browsers shall appear in the Web Browser tab, in the line of what happens with recordings.

**Comment by micaelgallego** [comment]
Specifically, manual opened browsers should appear along the browsers opened using selenium RemoteWebdriver URL

**Comment by EduJGURJC** [comment]
Included since [1.0.0-beta4](https://elastest.io/docs/releases/#1.0.0-beta4) version
