### ISSUE TITLE
Sut metrics do not show up in the dashboard

### ISSUE THREAD

**Issue by pchico83** [elastest/elastest#13]
The missing metrics happen when the Sut is deployed by Elastest using a compose file.

**Comment by EduJGURJC** [comment]
Hi @pchico83, for this case you need to add the compose services metrics cards manually.

**Comment by EduJGURJC** [comment]
Hi @pchico83, for this case you need to add the compose services metrics cards manually.
For do this, you need to click in "Open Monitoring Config", the "nut" button at the top right of the page

![image](https://user-images.githubusercontent.com/26252085/40228142-be399caa-5a90-11e8-9181-51adda08324b.png)

**Comment by pchico83** [comment]
@EduJGURJC This is what I get after clicking the "nut" button:
<img width="1155" alt="screen shot 2018-05-18 at 11 47 39" src="https://user-images.githubusercontent.com/7474696/40228369-5f4db450-5a91-11e8-933e-28d3fa226dae.png">

**Comment by EduJGURJC** [comment]
Can you open the browser console and clean it before clicking on "Open monitoring configuration" to check for errors, please?

**Comment by pchico83** [comment]
I made it working now.
I would unify how different metrics are handled.
For example, the tjob metrics can be specified in the tjob config, but the sut metrics are not.
Also, in the test execution there is a chart configuration button and also the "nut" button for advanced usage. I would configure both of them on the same way.

**Comment by EduJGURJC** [comment]
thanks for your feedback @pchico83
