### ISSUE TITLE
ElasTest doesn't start on Mac

### ISSUE THREAD

**Issue by micaelgallego** [elastest/elastest#17]
When ElasTest is executed with the following command (described in the docs):

<pre>$ docker run --rm -v /var/run/docker.sock:/var/run/docker.sock elastest/platform start --logs</pre>

The result is:

<pre>
Pulling some necessary images...

Preload images finished.

Starting ElasTest Platform 1.0.0-beta1 (normal mode)...

Creating network "elastest_elastest" with driver "bridge"
Creating elastest_etm-filebeat_1      ... done
Creating elastest_edm-mysql_1         ... done
Creating elastest_platform-services_1 ... done
Creating elastest_etm_1               ... error

ERROR: for elastest_etm_1  Cannot start service etm: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/etc/localtime\\\" to rootfs \\\"/var/lib/docker/overlay2/be2b78bf92986f2e50a0564e256593aa77113042f977a4acf6a14726f792dfc4/merged\\\" at \\\"/var/lib/docker/overlay2/be2b78bf92986f2e50a0564e256593aa77113042f977a4acf6a14726f792dfc4/merged/etc/localtime\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for etm  Cannot start service etm: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/etc/localtime\\\" to rootfs \\\"/var/lib/docker/overlay2/be2b78bf92986f2e50a0564e256593aa77113042f977a4acf6a14726f792dfc4/merged\\\" at \\\"/var/lib/docker/overlay2/be2b78bf92986f2e50a0564e256593aa77113042f977a4acf6a14726f792dfc4/merged/etc/localtime\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
Encountered errors while bringing up the project.
</pre>

**Comment by EduJGURJC** [comment]
Fixed for the next release and for the development version
