### ISSUE TITLE
Execution Tjob, user can not use private repository for execute test

### ISSUE THREAD

**Issue by KarolCzarnecki** [elastest/elastest#23]
When user want to use private git repository in Tjob to clone existing tests and run them from elastest process fails. Is there any user-friendly way to insert credentials etc which let user to user private github?

**Comment by EduJGURJC** [comment]
Hi @KarolCzarnecki. No, for this you must manage the credentials from the container's own code in **Commands**

**Comment by micaelgallego** [comment]
Also, remember that you can "connect" ElasTest to Jenkins. In that way, you manage credentials in Jenkins job and use ElasTest for test monitoring
