### ISSUE TITLE
Use the same test case name in different test suites

### ISSUE THREAD

**Issue by Maes95** [elastest/elastest#26]
Right now, if I run several test cases with the same name, each one in different test suites, Elastest takes the metrics and logs only from the first for all.

An improvement would be that the trace used to differentiate logs and test case metrics would change from being:
```
##### Start test: <test_case_name>
```
to
```
##### Start test: <test_suite_name>_<test_case_name>
```

**Comment by EduJGURJC** [comment]
Hi @Maes95,

This functionality has been implemented and is now available in ElasTest dev, it will soon be available in the next stable version (2.0.0)
