### ISSUE TITLE
TSS containers remain active when ElasTest stops.

### ISSUE THREAD

**Issue by LordWire** [elastest/elastest#6]
**Elastest version:** dev (20180425). This was also noticed by @gtunon a long time ago but we just reproduced it.
**Elastest mode:** experimental
**Tested TSS:** EBS
OS: Fedora 27 / MacOS High Sierra (tested on both).

When a TJob starts a TSS internally and the TJob is never finished (e.g. killed/failed), this TSS is not stopped when ElasTest is stopped. As a result, in subsequent TJob executions new TSS containers are launched and the old ones are ignored. This ends up creating several different issues, but the more important one is that nightly gets filled with orphaned running containers during every code update. 

Steps to reproduce:

1. Launch ElasTest in experimental mode.
2. Create a TJob that will launch its own TSS (don't start a TSS from 'Support Services' menu). This is tested with EBS.
3. Launch the TJob and stop it while it is executing. At this point, the TSS containers remain active.
4. Stop ElasTest and run a `docker ps`. The TSS containers are still running.
5. Restart ElasTest and repeat the procedure. When the TJob is re-executed, a new set of TSS images will be launched. 

This is related to and will trigger #4 .

**Comment by gortazar** [comment]
This is a bug we are aware of. Can you give it a try with the new 0.9.1 version?

Steps to update can be found in the Update section [here](https://elastest.io/docs/try-elastest/).
